### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by SpaceLearner** [LibRerank-Community/LibRerank#1]
LibRerank# bash example/run_ranker.sh
num of item 349404 num of list 483049 profile num 8 spar num 5 dens num 1
Tree 0
example/run_ranker.sh: line 1: 2477587 Segmentation fault

**Comment by YunjiaXi** [comment]
As my code works well here and there are many reasons for the segmentation fault, I am not entirely sure what is causing it. So I would appreciate it if you could provide some specific information, like memory, packages, and their versions in your environment.
Also, one possible reason is the multiprocessing used in lambdamart. Multiprocessing and lack of memory sometimes cause the segment fault. Try running DNN ranker: python run_init_ranker.py --setting_path=./example/config/ad/dnn_setting.json.
If the DNN ranker is OK, the problem should be caused by lambdamart. Then you can try to remove multiprocessing from lambdamart or use a machine with more memory.
